name: Ask a question
description: Ask a question about Intent Architect
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Remember :
        * Please make your question as clear and specific as possible.
        * Please check that the [documentation](https://docs.intentarchitect.com/) or [answered support tickets](https://github.com/IntentArchitect/Support/issues) does not answer your question.
  - type: textarea
    id: question
    attributes:
      label: Ask a question
    validations:
      required: true
