name: Log an issue
description: Notify us of any bugs or issues found in Intent Architect or our Modules
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: issue_impact
    attributes:
      label: "How is This Issue Affecting You?"
      description: "Select the option that best describes the impact of this issue on your work."
      options:
        - "❌ I am completely blocked and need urgent help (Critical)"
        - "⏳ This slows me down, but I can still make progress (Major)"
        - "✅ I have a workaround, but a fix would be ideal (Minor)"
        - "✨ This is a suggestion or nice-to-have improvement (Enhancement)"
    validations:
      required: true      
  - type: input
    id: intentArchitectVersion
    attributes:
      label: What version of Intent Architect are you using?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Additional information
      description: Please provide as any relevant information you think would help us resolve this issue (e.g. reproduction steps, screenshots, SF output, etc.)
    validations:
       required: false
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
