name: Feature request
description: Suggest an idea for Intent Architect
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: problem-space
    attributes:
      label: What problem are you trying to solve?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what the problem is.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe the solution you'd like
      placeholder: Tell us how you think the solution should look like
    validations:
      required: true
