name: Feature request
description: Suggest an idea for Intent Architect
labels: [enhancement]
body:
  - type: textarea
    id: problem-space
    attributes:
      label: What problem are you trying to solve?
      placeholder: Tell us what the problem is.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe the solution you'd like
      placeholder: Tell us how you think the solution should look like
    validations:
      required: true
